name: DocstrCoverage

on: [push, pull_request]

permissions:
  contents: write
  statuses: write

jobs:
  check-docstring-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install docstr-coverage

    - name: Run docstring coverage check
      id: coverage
      run: |
        coverage=$(python unitTest/docstringCoverage.py secureRequests | tail -n 1 | tr -d '\r\n')
        echo "Extracted Coverage: ${coverage}%"
        echo "coverage=${coverage}" >> $GITHUB_ENV

    - name: Upload results as status
      uses: actions/github-script@v7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        script: |
          const coverage = process.env.coverage;
          const commitSha = process.env.GITHUB_SHA;
          await github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: commitSha,
            state: 'success',
            context: 'DocstringCoverage',
            description: `DocstrCoverage: ${coverage}%`
          });
